### PR TITLE
fix: Support quoted attribute names

### LINKED ISSUE #126: all: quoted attribute names are not supported correctly
### What Happened?

In numerous places, attribute names are required and formatted using `fmt.Sprintf()` directly. This is broken with usage of quoted attribute names that have characters like dots in them, and possibly spaces, since it leads to Nix not understanding what attributes to query or invalid command invocation.

### How To Reproduce

Applying attribute names for `nixosConfigurations.<host>` for example; a `NIXOS_CONFIG` set to `/home/varun/.nixed#nixosConfigurations."Charles Woodson"` results in an invalid syntax error.

Also, evaluating option values with `optnix`'s evaluator function, the same thing can happen.

### Expected Behavior

Attribute names that need quotes will be quoted properly in command invocations.

This can be done by replacing all raw `fmt.Sprintf()` calls with a special attribute formatting function. of some sort.

### Features

```shell
<not applicable>
```

### PR DESCRIPTION
**Pull request by Sporif**
This PR introduces support for Nix attribute names containing spaces and dots. It involves creating two new types to represent attribute names and paths, and replacing `fmt.Sprintf()` calls with functions that use these types. It also adds `FlakeRef` and `LegacyConfiguration` functions to format common NixOS configuration attributes. 

I have tested local flake and legacy builds, images, specialisations, VMs, and evaluation of option values. I have not tested remote building (but it should also work).

Closes #126.

### CODE REVIEW

File: internal/utils/utils.go [hunk 1]
```diff
@@ -60,6 +60,71 @@ func Quote(s string) string {
 	return s
 }
 
+type NixAttrName string
```
Comment (water-sucks) [inline internal/utils/utils.go]: The vast majority of Nix attribute params eventually coerce down to strings, so I think the extra types like this one and `NixAttrPath` make this slightly unclear, and the type conversions to satisfy the type checker are more fluff than they are useful.

While I get that Join() could potentially be a useful method, it's currently not used anywhere, and I think using strictly strings only for these functions would be a cleaner way of handling this attribute joining. Definitely willing to discuss this though, but I don't currently see the benefits of using a new type, since it's just an alias for string.

File: internal/utils/utils.go [hunk 2]
```diff
@@ -60,6 +60,71 @@ func Quote(s string) string {
...
+
+var specialAttrCharsPattern = regexp.MustCompile(`[. ]`)
+
+// Create a Nix attribute name by quoting the string s if it contains
+// dots or spaces.
+func NewNixAttrName(s string) NixAttrName {
+	if strings.HasPrefix(s, "\"") && strings.HasSuffix(s, "\"") ||
+		!specialAttrCharsPattern.MatchString(s) {
```
Comment (water-sucks) [inline internal/utils/utils.go]: It is possible for attribute names to only have digits in them, or to start with one. These are invalid attribute paths without quoting, so this needs to be added to the rules for quoting as well.

File: internal/utils/utils.go [hunk 3]
```diff
@@ -60,6 +60,71 @@ func Quote(s string) string {
...
+		return NixAttrName(s)
+	}
+
+	return NixAttrName("\"" + s + "\"")
```
Comment (water-sucks) [inline internal/utils/utils.go]: Simple quoting like this does not escape the quote (`"`) character itself, were it to be contained inside the attribute name. You will need to escape those here as well.

File: internal/utils/utils.go [hunk 4]
```diff
@@ -60,6 +60,71 @@ func Quote(s string) string {
...
+
+func (n NixAttrName) String() string {
+	return string(n)
+}
+
+type NixAttrPath string
+
+// Create a Nix attribute path by joining attribute names with dots
+// and ignoring any empty attributes names.
+func NewNixAttrPath(a ...any) NixAttrPath {
```
Comment (water-sucks) [inline internal/utils/utils.go]: `any` here as a type does not seem the best, since other string types that are just string-aliases may need to be coerced and this conversion is done at runtime with the type switch for every value.

Instead, we can enforce any string-like type with generics using `~string` to make this more transparent:

```suggestion
func NewNixAttrPath[T ~string](values ...T) string {
```

Something like this.

Also, nit: I feel like the name `MakeNixAttrPath` is slightly better a name if we do decide to use `[~string]`? But feel free to disregard.

File: internal/utils/utils.go [hunk 5]
```diff
@@ -60,6 +60,71 @@ func Quote(s string) string {
...
+
+func (p NixAttrPath) Join(attrPath NixAttrPath) NixAttrPath {
+	if len(attrPath) == 0 {
+		return p
+	} else if len(p) == 0 {
+		return attrPath
+	} else {
+		return p + "." + attrPath
+	}
+}
```
Comment (water-sucks) [inline internal/utils/utils.go]: This is unused from what I can tell. It may be redundant since a join function already exists with `NewNixAttrPath()`.


```suggestion
```

File: internal/utils/utils_test.go
Comment (water-sucks) [inline internal/utils/utils_test.go:1]: `utils_test` is too generic a name since this only tests the join attrs utils. Might be better to name this `join_attrs_test.go` or something similar that conveys intent better.

I don't like `utils` packages in general (see https://www.yanglinzhao.com/posts/utils-antipattern//) but I was too lazy at the time to separate everything into proper packages, so it's my fault really.

**Review by water-sucks — CHANGES_REQUESTED** [review]
This is a good start! Really appreciate the time you took for this so far.

File: internal/utils/utils_test.go
Comment (Sporif) [reply internal/utils/utils_test.go:1]: Perhaps I should make a new package e.g `nix.go` and `nix_test.go`. And remove the `Nix` part from the types and functions, e.g.: `nix.MakeAttrPath`. Is that ok?

File: internal/utils/utils.go (hunk 5 above)
Comment (Sporif) [reply internal/utils/utils.go]: This is left over from earlier versions, before I replaced all usage with `NewNixAttrPath`. I'll remove it.

File: internal/utils/utils.go (hunk 1 above)
Comment (Sporif) [reply internal/utils/utils.go]: `NixAttrPath` is needed to differentiate between an attr name with dots and an attr path. Otherwise, `NewNixAttrPath` would not be able to handle attr paths, as `NewNixAttrName` would escape them. 
We would have to make sure to never pass to `NewNixAttrPath` any strings that could be attr paths (e.g `buildType.BuildAttr()`, or `attr` arg of `EvalAttribute`), and instead use another function to combine them instead. I think this would be somewhat fragile, but perhaps there is a better alternative I'm not aware of.

On the other hand, `NixAttrName` could be removed, but it might be slightly less efficient as `NewNixAttrName` would be called already on already quoted attr names in `NewNixAttrPath`.

File: internal/utils/utils.go (hunk 4 above)
Comment (Sporif) [reply internal/utils/utils.go]: If we get rid of the new types, then yes generics should work here.

File: internal/utils/utils.go (hunk 3 above)
Comment (Sporif) [reply internal/utils/utils.go]: ~~Yeah I only tested flake.nix host attributes, which don't seem to accept `"`. Silly me for not remembering [flake.nix is not actually written in nix](https://github.com/NixOS/nix/issues/4945)~~.

Edit: Ok, it's actually a different issue, the `nix` command itself doesn't accept `"` in attribute path arguments. As a result I am not sure there's any point in escaping `"`.

File: internal/utils/utils_test.go
Comment (water-sucks) [reply internal/utils/utils_test.go:1]: Sure that works!

File: internal/utils/utils.go (hunk 3 above)
Comment (water-sucks) [reply internal/utils/utils.go]: Just tested, I didn't know this was a thing! Thanks for opening my eyes.

I don't think this will be a common situation anyway so this can be resolved without any issues I think.

File: internal/utils/utils.go (hunk 2 above)
Comment (water-sucks) [reply internal/utils/utils.go]: Same situation for these, I think this can be resolved since the Nix CLI tends to error out and think that number-only attributes quoted in strings are valid keys when evaluating, but not to address with dot-path syntax so yeah. Disregard my comment.

File: internal/utils/utils.go (hunk 1 above)
Comment (water-sucks) [reply internal/utils/utils.go]: This is fair enough. However, there's a solution for this: when combining, make sure to split out any components first before re-combining them. We may need a `func SplitAttrs(input string) string` function to facilitate this, where it can also split quoted terms.

This should let us use bare string types, and I don't think there's any performance implications to be worried about here since there's so few strings to combine in most instances.

Comment (Sporif) [reply internal/utils/utils.go]: Ok, I removed the types and added a `splitAttrPath` function. I think the original issue still exists with legacy configuration attributes though, as these can be either attribute paths or just singular attributes. If someone runs `nixos apply config.nix "foo.bar"` the attribute will be split when they might actually mean `"\"foo.bar\""`. My older implementation with types handled this even worse by simply assuming they were already escaped attribute paths. So I don't know if it can be solved.

Comment (water-sucks) [reply internal/utils/utils.go]: Hmm that probably is an issue with the  `nixosConfigurations.<host>` attribute as well, since I know many people tend to use hostnames for that and hostnames can contain periods.

A potential solution I thought of just now: `splitAttrPath()` can probably handle physical escapes with a `\` character, so something like `nixos apply '/home/user/config#nixosConfigurations."foo\\.bar"'` in bash would then be passed as `/home/user/config#nixosConfigurations."foo\.bar"` and then the escapes can be resolved in `splitAttrPath()`. It may be worth exporting this function as well in case it can be used anywhere else. I doubt users are using backslashes in their hostnames, but they can always double escape those I suppose.

We definitely need to document this behavior somewhere I think; maybe it will suffice on the `nixos-cli-env(5)` manpage where `NIXOS_CONFIG` is defined for now, but we can figure out a better place for it for sure.

Comment (Sporif) [reply internal/utils/utils.go]: > Hmm that probably is an issue with the nixosConfigurations.<host> attribute as well, since I know many people tend to use hostnames for that and hostnames can contain periods.

For the flake host attribute I have assumed a singular attribute name and used `MakeAttrName` so it is escaped if necessary. So I don't think it has the same issue and shouldn't require any escaping from the user. We could do the same for legacy attributes, that would certainly be much easier. Otherwise I will test out escaping with `\` as a solution.

As for the documentation, maybe it is better to put it in `nixos-cli(1)`, in a new `ARGUMENTS` section?

Comment (water-sucks) [reply internal/utils/utils.go]: Yeah I think that sounds good, feel free to make those changes and I think that should be good for this PR. Do add some new test cases for this situation as well, just to be a bit more exhaustive in that regard.

Thanks for taking the time for this.

Comment (Sporif) [reply internal/utils/utils.go]: Sorry, do you mean it's ok to use `MakeAttrName` on legacy attributes (i.e only accept single attribute names like flakes)? Or instead add escaping with `\` to be able to accept paths and names?

Comment (water-sucks) [reply internal/utils/utils.go]: No worries, I meant to add escaping with \ just in case, since I do think that having dots in names could be a more common occurrence than I initially thought.

Comment (Sporif) [reply internal/utils/utils.go]: I've made the changes.

File: cmd/apply/apply.go [hunk 6]
```diff
@@ -765,7 +766,7 @@ func getAvailableImageAttrs(
 	case *configuration.FlakeRef:
 		evalArgs := nixopts.NixOptionsToArgsListByCategory(cobraCmd.Flags(), nixOpts, "lock")
 
-		attr = fmt.Sprintf("%s#nixosConfigurations.%s.config.system.build.images", v.URI, v.System)
+		attr := v.BuildAttr("images")
```
Comment (water-sucks) [inline cmd/apply/apply.go]: This shadows the `attr` variable declaration and causes a slightly confusing error message if the command fails.
```suggestion
		attr = v.BuildAttr("images")
```

File: cmd/apply/apply.go [hunk 7]
```diff
@@ -810,11 +811,12 @@ func getImageName(
 	var argv []string
 	var attr string
 
+	imgName = nix.MakeAttrName(imgName)
 	switch v := cfg.(type) {
 	case *configuration.FlakeRef:
 		evalArgs := nixopts.NixOptionsToArgsListByCategory(cobraCmd.Flags(), nixOpts, "lock")
 
-		attr = fmt.Sprintf("%s#nixosConfigurations.%s.config.system.build.images.%s.passthru.filePath", v.URI, v.System, imgName)
+		attr := v.BuildAttr("images", imgName, "passthru", "filePath")
```
Comment (water-sucks) [inline cmd/apply/apply.go]: Same shadowing issue here.

```suggestion
		attr = v.BuildAttr("images", imgName, "passthru", "filePath")
```

**Review by water-sucks — CHANGES_REQUESTED** [review]
Couple of variable shadowing issues.

I'll enable a `golangci-lint` linter for this in the future, but it does tend to be rather strict. Strict may be better than lax in this case though, since Go's shadowing rules have already caused bugs in the past.

Edit: Done in #172

**Review by water-sucks — APPROVED** [review]
This is amazing now! I really appreciate your contributions thus far.
