### PR TITLE
fix(system): use wrapper for local env when necessary

### LINKED ISSUE #180: apply: necessary environment variables are not passed to `switch-to-configuration` with `--local-root` or `--remote-root`
This is due to the root command `sudo` resetting the environment. Other root commands, such as `run0` and `pkexec`, also reset the environment by default.

The environment variables in question are `NIXOS_INSTALL_BOOTLOADER`, `NIXOS_NO_CHECK`, and `NIXOS_CLI_ATTEMPTING_ACTIVATION`. 
In particular, not passing `NIXOS_INSTALL_BOOTLOADER` means `systemd-boot` or `grub` will not add an efi boot entry (`nixos-rebuild-ng` has the same [issue](https://github.com/NixOS/nixpkgs/issues/127827)).

I think one solution could be to use the `env` command to set these variables, as a prefix to `switch-to-configuration`. I don't think root command specific solutions, such as `sudo -E` or `env_keep`, are suitable (like `nixos-rebuild-ng` does with [NIXOS_NO_CHECK](https://github.com/NixOS/nixpkgs/pull/475295)).

You can workaround this issue by running `nixos apply` as root or setting `apply.reexec_as_root=true`.

### PR DESCRIPTION
**Pull request by water-sucks**
The current wrapper for setting variables through SSH env var sanitation barriers works pretty well in that instance, but needed to be expanded to work with local systems so that it can pass through `sudo`/other root escalation barriers as well, since those tend to sanitize the environment variables for the subprocess they run.

As such, this PR adds tests for the now-exported shell wrapper builder, and makes all systems use it when environment variables need to be passed through these barriers. I added an extra method to inherit environment variables explicitly when necessary as well, although this does need to be done on a per-process and opt-in basis, since I do not want to risk breaking subcommand invariants when they are invoked through `sudo` (i.e. `sudo` rewrites the HOME of the process to be `/root`, so we shouldn't preserve that; things like that that are more of a hassle to maintain than just opting-in to env var preservation).

Closes #180, for real this time hopefully.

### CODE REVIEW

**Comment by water-sucks** [comment]
@Sporif I would really appreciate your input on this change, since you reported the issue as well.

File: internal/system/local.go [hunk 1]
```diff
@@ -50,7 +65,7 @@ func (l *LocalSystem) Run(cmd *Command) (int, error) {
 		command.Env = append(command.Env, key+"="+value)
 	}
```
Comment (Sporif) [inline internal/system/local.go]: This is redundant if `cmd.RootElevationCmd` is set. It's probably harmless but something to note.

File: internal/system/ssh.go [hunk 2]
```diff
@@ -500,69 +505,6 @@ func requestRootPasswordPTY(session *ssh.Session, stdin io.Reader) (func(), erro
 
 var envVarNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)
```
Comment (Sporif) [inline internal/system/ssh.go]: Nit: perhaps this should also be moved to `runner.go`.

**Comment by Sporif** [comment]
It now works perfectly for local and remote activation, thanks! I just had two small nits, feel free to ignore them.

**Comment by water-sucks** [comment]
> I just had two small nits, feel free to ignore them.

I think they might have disappeared or something? Don't see them at all. I'll just request you for review and you can post them as an actual review requesting changes :}

**Comment by Sporif** [comment]
> > I just had two small nits, feel free to ignore them.
> 
> I think they might have disappeared or something? Don't see them at all. I'll just request you for review and you can post them as an actual review requesting changes :}

Sorry, I forgot to press submit review 😅.

**Comment by water-sucks** [comment]
> Sorry, I forgot to press submit review 😅.

All good! I'm gonna merge this since you have tested it a bit; I've also done some testing on my own end and everything seems to check out.
